"""
Embedded movie dataset for the recommendation engine.

Each entry has: title, genres (list of strings), and a short overview.
This keeps the whole project self-contained (no external dataset
download or API key required). Feel free to extend this list with
more movies, or swap it out for a full dataset like MovieLens or
TMDB later (see README.md for notes on that).
"""

MOVIES = [
    {"title": "The Shawshank Redemption", "genres": ["Drama"], "overview": "Two imprisoned men bond over years, finding solace and eventual redemption through acts of common decency."},
    {"title": "The Godfather", "genres": ["Crime", "Drama"], "overview": "The aging patriarch of an organized crime dynasty transfers control to his reluctant son."},
    {"title": "The Dark Knight", "genres": ["Action", "Crime", "Drama", "Thriller"], "overview": "Batman must accept one of the greatest psychological tests to fight injustice against the Joker."},
    {"title": "Pulp Fiction", "genres": ["Crime", "Drama"], "overview": "The lives of two mob hitmen, a boxer, and others intertwine in tales of violence and redemption."},
    {"title": "Forrest Gump", "genres": ["Drama", "Romance"], "overview": "The presidencies of Kennedy and Johnson unfold through the perspective of an Alabama man with a low IQ."},
    {"title": "Inception", "genres": ["Action", "Adventure", "Sci-Fi", "Thriller"], "overview": "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea."},
    {"title": "Fight Club", "genres": ["Drama"], "overview": "An insomniac office worker and a soap maker form an underground fight club that evolves into something much more."},
    {"title": "The Matrix", "genres": ["Action", "Sci-Fi"], "overview": "A hacker learns the true nature of reality and his role in the war against its controllers."},
    {"title": "Goodfellas", "genres": ["Biography", "Crime", "Drama"], "overview": "The story of Henry Hill and his life in the mob, covering his relationship with his wife and partners."},
    {"title": "Interstellar", "genres": ["Adventure", "Drama", "Sci-Fi"], "overview": "A team of explorers travel through a wormhole in space to ensure humanity's survival."},
    {"title": "The Lord of the Rings: The Fellowship of the Ring", "genres": ["Adventure", "Fantasy"], "overview": "A hobbit sets out with companions to destroy a powerful ring before it falls into the wrong hands."},
    {"title": "Star Wars: A New Hope", "genres": ["Action", "Adventure", "Fantasy", "Sci-Fi"], "overview": "Luke Skywalker joins forces with a Jedi Knight to rescue a princess and save the galaxy from an evil empire."},
    {"title": "Se7en", "genres": ["Crime", "Drama", "Mystery", "Thriller"], "overview": "Two detectives hunt a serial killer who uses the seven deadly sins as his motives."},
    {"title": "The Silence of the Lambs", "genres": ["Crime", "Drama", "Thriller"], "overview": "A young FBI trainee seeks the help of an incarcerated cannibal killer to catch another serial murderer."},
    {"title": "Saving Private Ryan", "genres": ["Drama", "War"], "overview": "Following the Normandy landings, soldiers go behind enemy lines to retrieve a paratrooper whose brothers have died."},
    {"title": "The Green Mile", "genres": ["Crime", "Drama", "Fantasy"], "overview": "The lives of guards on death row are affected by one of their charges, a black man accused of murder with a mysterious gift."},
    {"title": "Gladiator", "genres": ["Action", "Adventure", "Drama"], "overview": "A former Roman general sets out to exact vengeance against the corrupt emperor who murdered his family."},
    {"title": "The Departed", "genres": ["Crime", "Drama", "Thriller"], "overview": "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang."},
    {"title": "The Prestige", "genres": ["Drama", "Mystery", "Sci-Fi"], "overview": "Two stage magicians engage in competitive one-upmanship in an attempt to create the ultimate stage illusion."},
    {"title": "Whiplash", "genres": ["Drama", "Music"], "overview": "A promising young drummer enrolls at a music conservatory and is mentored by a ruthless, demanding instructor."},
    {"title": "The Social Network", "genres": ["Biography", "Drama"], "overview": "The founding of Facebook and the resulting lawsuits between the co-founders and other claimants."},
    {"title": "Parasite", "genres": ["Comedy", "Drama", "Thriller"], "overview": "Greed and class discrimination threaten the newly formed symbiotic relationship between a wealthy family and a poor one."},
    {"title": "Joker", "genres": ["Crime", "Drama", "Thriller"], "overview": "A mentally troubled comedian embarks on a downward spiral of revolution and bloody crime in Gotham City."},
    {"title": "Get Out", "genres": ["Horror", "Mystery", "Thriller"], "overview": "A young African-American visits his white girlfriend's family estate, uncovering a sinister secret."},
    {"title": "La La Land", "genres": ["Comedy", "Drama", "Music", "Romance"], "overview": "A jazz pianist and an aspiring actress fall in love while pursuing their dreams in Los Angeles."},
    {"title": "Mad Max: Fury Road", "genres": ["Action", "Adventure", "Sci-Fi"], "overview": "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland."},
    {"title": "The Grand Budapest Hotel", "genres": ["Adventure", "Comedy", "Drama"], "overview": "The adventures of a legendary concierge at a famous European hotel and the lobby boy who becomes his trusted friend."},
    {"title": "Coco", "genres": ["Animation", "Adventure", "Family", "Fantasy", "Music"], "overview": "A boy is accidentally transported to the land of the dead, seeking the help of his musician great-great-grandfather."},
    {"title": "Toy Story", "genres": ["Animation", "Adventure", "Comedy", "Family", "Fantasy"], "overview": "A cowboy doll feels threatened when a new spaceman action figure supplants him as top toy in a boy's room."},
    {"title": "Up", "genres": ["Animation", "Adventure", "Comedy", "Family"], "overview": "A widower ties balloons to his house and flies to South America to fulfill a promise made to his late wife."},
    {"title": "WALL-E", "genres": ["Animation", "Adventure", "Family", "Sci-Fi"], "overview": "A robot left to clean an abandoned Earth discovers a new purpose when he falls in love with another robot."},
    {"title": "Spirited Away", "genres": ["Animation", "Adventure", "Family", "Fantasy"], "overview": "A young girl wanders into a world ruled by gods and witches, working in a bathhouse to free her parents."},
    {"title": "The Lion King", "genres": ["Animation", "Adventure", "Drama", "Family"], "overview": "A lion cub who will one day be king flees his kingdom after his father's murder, only to learn the true meaning of responsibility."},
    {"title": "Finding Nemo", "genres": ["Animation", "Adventure", "Comedy", "Family"], "overview": "After his son is captured, a timid clownfish sets out on a journey to bring him home."},
    {"title": "Shrek", "genres": ["Animation", "Adventure", "Comedy", "Family", "Fantasy"], "overview": "A grumpy ogre agrees to rescue a princess for a villainous lord in order to save his swamp."},
    {"title": "Titanic", "genres": ["Drama", "Romance"], "overview": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the ill-fated R.M.S. Titanic."},
    {"title": "The Notebook", "genres": ["Drama", "Romance"], "overview": "A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom."},
    {"title": "Pride and Prejudice", "genres": ["Drama", "Romance"], "overview": "Sparks fly when spirited Elizabeth Bennet meets the proud Mr. Darcy in this classic tale of manners and misunderstanding."},
    {"title": "La Vie en Rose", "genres": ["Biography", "Drama", "Music"], "overview": "The life of French singer Edith Piaf, from her impoverished childhood to her rise to fame."},
    {"title": "Amelie", "genres": ["Comedy", "Romance"], "overview": "A shy waitress decides to change the lives of those around her for the better while struggling with her own isolation."},
    {"title": "Superbad", "genres": ["Comedy"], "overview": "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a party goes awry."},
    {"title": "Bridesmaids", "genres": ["Comedy", "Romance"], "overview": "Competition between the maid of honor and a bridesmaid over who is the bride's best friend threatens to upend the wedding."},
    {"title": "The Hangover", "genres": ["Comedy"], "overview": "Three friends wake up from a bachelor party in Las Vegas with no memory of the previous night, and their friend is missing."},
    {"title": "Anchorman", "genres": ["Comedy"], "overview": "San Diego's top-rated newsman is threatened by a new employee with ambition to succeed, and everything he knows is turned upside down."},
    {"title": "Dune", "genres": ["Action", "Adventure", "Sci-Fi"], "overview": "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset on a dangerous desert planet."},
    {"title": "Blade Runner 2049", "genres": ["Action", "Drama", "Mystery", "Sci-Fi"], "overview": "A young blade runner unearths a secret that has the potential to plunge what's left of society into chaos."},
    {"title": "Arrival", "genres": ["Drama", "Mystery", "Sci-Fi"], "overview": "A linguist is recruited by the military to communicate with alien lifeforms after twelve mysterious spacecraft appear."},
    {"title": "Ex Machina", "genres": ["Drama", "Sci-Fi", "Thriller"], "overview": "A programmer is selected to administer the Turing test to an intelligent humanoid robot."},
    {"title": "Her", "genres": ["Drama", "Romance", "Sci-Fi"], "overview": "A lonely writer develops an unlikely relationship with an operating system designed to meet his every need."},
    {"title": "Alien", "genres": ["Horror", "Sci-Fi"], "overview": "The crew of a commercial spacecraft encounter a deadly lifeform after investigating a distress signal on a distant moon."},
    {"title": "The Exorcist", "genres": ["Horror"], "overview": "When a young girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her daughter."},
    {"title": "A Quiet Place", "genres": ["Drama", "Horror", "Sci-Fi"], "overview": "A family must live in silence while hiding from creatures that hunt by sound."},
    {"title": "Hereditary", "genres": ["Drama", "Horror", "Mystery"], "overview": "A family unravels dark secrets after the death of their secretive grandmother, uncovering an ancestral curse."},
    {"title": "It", "genres": ["Horror"], "overview": "In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster that preys on children."},
    {"title": "John Wick", "genres": ["Action", "Crime", "Thriller"], "overview": "An ex-hitman comes out of retirement to track down the gangsters that killed his dog and took everything from him."},
    {"title": "Die Hard", "genres": ["Action", "Thriller"], "overview": "An NYPD officer tries to save his estranged wife and others taken hostage by terrorists during a Christmas party."},
    {"title": "Mission: Impossible - Fallout", "genres": ["Action", "Adventure", "Thriller"], "overview": "Ethan Hunt and his team race against time after a mission goes wrong, causing global consequences."},
    {"title": "Skyfall", "genres": ["Action", "Adventure", "Thriller"], "overview": "Bond's loyalty to M is tested as her past comes back to haunt her, threatening MI6 itself."},
    {"title": "The Bourne Identity", "genres": ["Action", "Mystery", "Thriller"], "overview": "A man is discovered floating in the sea with amnesia, and is drawn into a search for his true identity."},
    {"title": "Spider-Man: Into the Spider-Verse", "genres": ["Animation", "Action", "Adventure", "Family", "Sci-Fi"], "overview": "Teen Miles Morales becomes Spider-Man and joins forces with other spider-powered people from parallel dimensions."},
    {"title": "Avengers: Endgame", "genres": ["Action", "Adventure", "Drama", "Sci-Fi"], "overview": "The remaining Avengers assemble to reverse the damage caused by Thanos and restore order to the universe."},
    {"title": "Black Panther", "genres": ["Action", "Adventure", "Sci-Fi"], "overview": "T'Challa returns home to Wakanda to take his place as king, but a challenger threatens the fate of his nation."},
    {"title": "Guardians of the Galaxy", "genres": ["Action", "Adventure", "Comedy", "Sci-Fi"], "overview": "A group of intergalactic misfits must band together to save the galaxy from a powerful villain."},
    {"title": "Coraline", "genres": ["Animation", "Family", "Fantasy"], "overview": "A girl discovers an alternate version of her life through a secret door, which seems perfect at first but hides a dark secret."},
]
